### ISSUE TITLE
no working, cursor remain as default

### ISSUE THREAD

**Issue by BenGedi** [therealmarv/vscode-theme-dark-atom-dark-green-cursor#1]
can't see any change :/

**Comment by therealmarv** [comment]
what version do you use and did you restarted whole vscode? I can see no problems here on my side (mac, vscode 1.19.1)

**Comment by BenGedi** [comment]
yes on vscode 1.19.1, and i've restarted whole vscode :/

**Comment by therealmarv** [comment]
bug is not reproducible.
