### ISSUE TITLE
It dosn't install correctly.

### ISSUE THREAD

**Issue by HannesDahlvik** [therealmarv/vscode-theme-dark-atom-dark-green-cursor#3]
When I install the theme it says 
"Cannot read property "id" of undefined"

**Comment by therealmarv** [comment]
@HannesDahl My theme does not have any JS / TS code inside (only XML) which your error message is referring too. Do you only have this error on my color theme? I cannot reproduce it on a fresh vscode on my side.

**Comment by HannesDahlvik** [comment]
I've got it working now, I didn't apply it correctly.
